name: Daily Wellness Tip

on:
  schedule:
    - cron: "0 8 * * *"   # every day at 08:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Generate tip
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-4o-mini
        run: |
          npm i
          node scripts/generate-tip.mjs

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/daily.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: daily tip [skip ci]"
            git push
          fi
